- type: GUILD_TEXT
  value: 0
  description: 'a text channel within a server'
- type: DM
  value: 1
  description: 'a direct message between users'
- type: GUILD_VOICE
  value: 2
  description: 'a voice channel within a server'
- type: GROUP_DM
  value: 3
  description: 'a direct message between multiple users'
- type: GUILD_CATEGORY
  value: 4
  description: 'an organizational category that contains up to 50 channels'
- type: GUILD_ANNOUNCEMENT
  value: 5
  description: 'a channel that users can follow and crosspost into their own server (formerly news channels)'
- type: ANNOUNCEMENT_THREAD
  value: 10
  description: 'a temporary sub-channel within a GUILD_ANNOUNCEMENT channel'
- type: PUBLIC_THREAD
  value: 11
  description: 'a temporary sub-channel within a GUILD_TEXT or GUILD_FORUM channel'
- type: PRIVATE_THREAD
  value: 12
  description: 'a temporary sub-channel within a GUILD_TEXT channel that is only viewable by those invited and those with the MANAGE_THREADS permission'
- type: GUILD_STAGE_VOICE
  value: 13
  description: 'a voice channel for hosting events with an audience'
- type: GUILD_DIRECTORY
  value: 14
  description: 'the channel in a hub containing the listed servers'
- type: GUILD_FORUM
  value: 15
  description: 'Channel that can only contain threads'
- type: GUILD_MEDIA
  value: 16
  description: 'Channel that can only contain threads, similar to GUILD_FORUM channels'
