- type: DEFAULT
  value: 0
  deleteable: true
- type: RECIPIENT_ADD
  value: 1
  deleteable: false
- type: RECIPIENT_REMOVE
  value: 2
  deleteable: false
- type: CALL
  value: 3
  deleteable: false
- type: CHANNEL_NAME_CHANGE
  value: 4
  deleteable: false
- type: CHANNEL_ICON_CHANGE
  value: 5
  deleteable: false
- type: CHANNEL_PINNED_MESSAGE
  value: 6
  deleteable: true
- type: USER_JOIN
  value: 7
  deleteable: true
- type: GUILD_BOOST
  value: 8
  deleteable: true
- type: GUILD_BOOST_TIER_1
  value: 9
  deleteable: true
- type: GUILD_BOOST_TIER_2
  value: 10
  deleteable: true
- type: GUILD_BOOST_TIER_3
  value: 11
  deleteable: true
- type: CHANNEL_FOLLOW_ADD
  value: 12
  deleteable: true
- type: GUILD_DISCOVERY_DISQUALIFIED
  value: 14
  deleteable: true
- type: GUILD_DISCOVERY_REQUALIFIED
  value: 15
  deleteable: true
- type: GUILD_DISCOVERY_GRACE_PERIOD_INITIAL_WARNING
  value: 16
  deleteable: true
- type: GUILD_DISCOVERY_GRACE_PERIOD_FINAL_WARNING
  value: 17
  deleteable: true
- type: THREAD_CREATED
  value: 18
  deleteable: true
- type: REPLY
  value: 19
  deleteable: true
- type: CHAT_INPUT_COMMAND
  value: 20
  deleteable: true
- type: THREAD_STARTER_MESSAGE
  value: 21
  deleteable: false
- type: GUILD_INVITE_REMINDER
  value: 22
  deleteable: true
- type: CONTEXT_MENU_COMMAND
  value: 23
  deleteable: true
- type: AUTO_MODERATION_ACTION
  value: 24
  deleteable: true*
- type: ROLE_SUBSCRIPTION_PURCHASE
  value: 25
  deleteable: true
- type: INTERACTION_PREMIUM_UPSELL
  value: 26
  deleteable: true
- type: STAGE_START
  value: 27
  deleteable: true
- type: STAGE_END
  value: 28
  deleteable: true
- type: STAGE_SPEAKER
  value: 29
  deleteable: true
- type: STAGE_TOPIC
  value: 31
  deleteable: true
- type: GUILD_APPLICATION_PREMIUM_SUBSCRIPTION
  value: 32
  deleteable: true
- type: GUILD_INCIDENT_ALERT_MODE_ENABLED
  value: 36
  deleteable: true
- type: GUILD_INCIDENT_ALERT_MODE_DISABLED
  value: 37
  deleteable: true
- type: GUILD_INCIDENT_REPORT_RAID
  value: 38
  deleteable: true
- type: GUILD_INCIDENT_REPORT_FALSE_ALARM
  value: 39
  deleteable: true
- type: PURCHASE_NOTIFICATION
  value: 44
  deleteable: true
- type: POLL_RESULT
  value: 46
  deleteable: true