commands:
  - name: links        
    description: Manage URL links stored in the database.
    triggerEvent: 
      event: MESSAGE_CREATE
    source: command
    group: links
    actions:
      - type: HTTP_REQUEST
        apiType: component_message
        dataType: message
        data:
          flags: 32768
          components:
            - type: 1
              components:
                - type: 2
                  label: Add Link
                  style: 1
                  custom_id: add_link
                - type: 2
                  label: Get Links
                  style: 1
                  custom_id: get_links
                - type: 2
                  label: Get Link Group
                  style: 1
                  custom_id: get_link_group
                - type: 2
                  label: Remove Link
                  style: 4
                  custom_id: remove_link

interactions:
  - name: add_link
    description: Add new link to the database.
    triggerEvent: 
      event: INTERACTION_CREATE
      type: 3
    source: interaction
    group: links
    actions:
      - type: HTTP_REQUEST
        apiType: interaction_response
        dataType: interaction_request
        data:
          type: 9
          data:
            custom_id: "links_input"
            title: "Input New Link"
            components:
              - type: 1
                components:
                  - type: 4
                    custom_id: "link_name"
                    label: "Link Name"
                    style: 1
                    min_length: 1
                    max_length: 100
                    placeholder: "What will be displayed as the text for the hyperlink"
                    required: true
              - type: 1
                components:
                  - type: 4
                    custom_id: "link_url"
                    label: "Link URL"
                    style: 1
                    min_length: 1
                    max_length: 500
                    placeholder: "URL of the link"
                    required: true
              - type: 1
                components:
                  - type: 4
                    custom_id: "link_description"
                    label: "Link Description"
                    style: 2
                    min_length: 1
                    max_length: 500
                    placeholder: "Description of the link"
                    required: false
              - type: 1
                components:
                  - type: 4
                    custom_id: "link_group"
                    label: "Link Group"
                    style: 1
                    min_length: 1
                    max_length: 100
                    placeholder: "Group of the link. Used to group up related links"
                    required: true

  - name: links_input
    description: Initial response to the Submit Modal interaction for add_link
    triggerEvent: 
      event: INTERACTION_CREATE
      type: 5
    source: interaction
    group: links
    actions:
      - type: HTTP_REQUEST
        apiType: interaction_response
        dataType: interaction_request
        data:
          type: 6

          data: {}
      - type: DB_REQUEST
        apiType: None
        dataType: db_event
        data:
          response: True
          operation: create
          table: links
          data:
            member_id: "##member.user.id"
            name: "link_name"
            url: "link_url"
            description: "link_description"
            group: "link_group"
      - type: DB_HTTP
        final: True
        apiType: channel_message
        dataType: message
        data:
          content: "Link 'link_name' added successfully!"

  - name: get_links
    description: Retrieve all links from the database.
    triggerEvent: 
      event: INTERACTION_CREATE
      type: 3
    source: interaction
    group: links
    actions:
      - type: HTTP_REQUEST
        dataType: interaction_request
        apiType: interaction_response
        data:
          type: 4
          data:
            content: "Fetching all links..."
            flags: 64
      - type: DB_REQUEST
        apiType: None
        dataType: db_event
        data:
          response: True
          operation: get_all
          table: links
          data: {}
      - type: DB_HTTP
        final: True
        apiType: component_message
        dataType: message
        data:
          flags: 32768
          components:
            LOOP_RESULTS: #used for looping over the retrieved data and adding each section under this per loop.
              - type: 10
                content: "#group#  [#name#](#url#)   #description#"
              - type: 14
                divider: true
                spacing: 1

  - name: get_link_group
    description: Retrieve all links for a group from the database.
    triggerEvent: 
      event: INTERACTION_CREATE
      type: 3
    source: interaction
    groups: links
    actions:
      - type: HTTP_REQUEST
        apiType: interaction_response
        dataType: interaction_request
        data:
          type: 9
          data:
            custom_id: "links_input"
            title: "Input New Link"
            components:
              - type: 1
                components:
                  - type: 4
                    custom_id: "fetch_link_group"
                    label: "Link Name"
                    style: 1
                    min_length: 1
                    max_length: 100
                    placeholder: "What will be displayed as the text for the hyperlink"
                    required: true

  - name: fetch_link_group
    description: Response series for fetching a link group
    triggerEvent:
      event: INTERACTION_CREATE
      type: 5
    source: interaction
    group: links
    actions:
      - type: HTTP_REQUEST
        dataType: interaction_request
        apiType: interaction_response
        data:
          type: 4
          data:
            content: "Fetching all links..."
            flags: 64

      - type: DB_REQUEST
        apiType: None
        dataType: db_event
        data:
          operation: get
          table: links
          data:
            group: "#link_group#"

      - type: DB_HTTP
        final: True
        apiType: component_message
        dataType: message
        data:
          flags: 32768
          components:
            LOOP_RESULTS: #used for looping over the retrieved data and adding each section under this per loop.
              - type: 10
                content: "#group#  [#name#](#url#)   #description#"
              - type: 14
                divider: true
                spacing: 1

  
  
  # - name: add_item
  #   description: Add new item to the AustinDepot.
  #   type: DB_HTTP
  #   apiType: interaction_callback
  #   triggerEvent: 
  #     event: INTERACTION_CREATE
  #     type: 3
  #   data_type: message
  #   source: interaction
  #   data:
  #     initial:
  #       description: "Initial item entry message"
  #       type: HTTP_REQUEST
  #       dataType: message
  #       source: interaction
  #       apiType: interaction_callback
  #       data:
  #         type: 9
  #         data:
  #           custom_id: "AustinDepotInput"
  #           title: "AustinDepot Item Entry"
  #           components:
  #             - type: 1
  #               components:
  #                 - type: 4
  #                   custom_id: "item_name"
  #                   label: "Item Name"
  #                   style: 1
  #                   min_length: 1
  #                   max_length: 150
  #                   placeholder: "Name of the swag"
  #                   required: true
  #             - type: 1
  #               components:
  #                 - type: 4
  #                   custom_id: "item_description"
  #                   label: "Item Description"
  #                   style: 2
  #                   min_length: 1
  #                   max_length: 500
  #                   placeholder: "Describe the swag item"
  #                   required: true
  #             - type: 1
  #               components:
  #                 - type: 4
  #                   custom_id: "item_quantity"
  #                   label: "Item Quantity"
  #                   style: 1
  #                   min_length: 1
  #                   max_length: 10
  #                   placeholder: "Number of items available"
  #                   required: true
  #             - type: 1
  #               components:
  #                 - type: 4
  #                   custom_id: "item_price"
  #                   label: "Item Price"
  #                   style: 1
  #                   min_length: 1
  #                   max_length: 500
  #                   placeholder: "Price of the item"
  #                   required: false
  #     follow_up:
  #       # might need something here to show that its loading in the original message.
  #       - description: "Insert new link data into the database"
  #         type: DB_REQUEST
  #         apiType: None
  #         triggerEvent: 
  #           event: INTERACTION_CREATE
  #           type: 5
  #         dataType: db_event
  #         source: interaction
  #         data:
  #           operation: create
  #           table: austin_depot
  #           data:
  #             name: "{#item_name#}"
  #             description: "{#item_description#}"
  #             quantity: "{#item_quantity#}"
  #             price: "{#item_price#}"

  #       - description: "Send confirmation message"
  #         type: HTTP_REQUEST
  #         apiType: message
  #         triggerEvent: 
  #           event: INTERACTION_CREATE
  #           type: 5
  #         dataType: message
  #         source: interaction
  #         data:
  #           type: 4
  #           data:
  #             content: "Item '{#item_name#}' added successfully!"
  #             flags: 64
