- code: 4001
  description: Unknown opcode
  explanation: You sent an invalid opcode.
- code: 4002
  description: Failed to decode payload
  explanation: You sent an invalid payload in your identifying to the Gateway.
- code: 4003
  description: Not authenticated
  explanation: You sent a payload before identifying with the Gateway.
- code: 4004
  description: Authentication failed
  explanation: The token you sent in your identify payload is incorrect.
- code: 4005
  description: Already authenticated
  explanation: You sent more than one identify payload. Stahp.
- code: 4006
  description: Session no longer valid
  explanation: Your session is no longer valid.
- code: 4009
  description: Session timeout
  explanation: Your session has timed out.
- code: 4011
  description: Server not found
  explanation: We can't find the server you're trying to connect to.
- code: 4012
  description: Unknown protocol
  explanation: We didn't recognize the protocol you sent.
- code: 4014
  description: Disconnected
  explanation: Channel was deleted
- code: 4015
  description: Voice server crashed
  explanation: The server crashed. Our bad! Try resuming.
- code: 4016
  description: Unknown encryption mode
  explanation: We didn't recognize your encryption.
